global:
  scrape_interval: ${SCRAPE_INTERVAL}
  scrape_timeout: ${SCRAPE_TIMEOUT}
  evaluation_interval: ${EVALUATION_INTERVAL}
  external_labels:
    monitor: codelab-monitor
scrape_configs:
- job_name: prometheus
  scrape_interval: ${SCRAPE_INTERVAL}
  scrape_timeout: ${SCRAPE_TIMEOUT}
  metrics_path: /metrics
  scheme: http
  file_sd_configs:
  - files:
    - ${SERVICE_DISCOVERY_FILE}
    refresh_interval: ${SERVICE_DISCOVERY_REFRESH_INTERVAL}